# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TruckYeah' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TruckYeah
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage' 

  pod 'BNRDeferred', '~> 3.0-beta'

  target 'TruckYeahTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TruckYeahUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
