CREATE TABLE Users (
	Username VARCHAR(250) PRIMARY KEY,
	Email VARCHAR(250) UNIQUE,
	Password VARCHAR(250) NOT NULL
)

CREATE TABLE FoodTruck (
	username VARCHAR(250) NOT NULL,
	Name VARCHAR(250) PRIMARY KEY,
	Description TEXT NOT NULL
)

CREATE TABLE FoodTruckImages (
	Foodtruckname VARCHAR(250) PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	image LONGBLOB NOT NULL
)

CREATE TABLE FoodTruckMenu (
	Foodtruckname VARCHAR(250) PRIMARY KEY,
	Name VARCHAR(250) PRIMARY KEY,
	Price VARCHAR(250) NOT NULL,
	FOREIGN KEY (Foodtruckname) REFERENCES FoodTruck(Name)
)
